name: Build

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Configure Node"
        uses: actions/setup-node@v2
        with: 
          node-version: 16

      - name: setup
        run: npm ci
        
      - name: release
        run: npm run release
